name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run build
      - run: mv build docs
      - run: git config --global user.name "github-actions[bot]"
      - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git add docs
      - run: git commit -m 'React build $(git rev-parse --short "$GITHUB_SHA")'
      - run: git checkout -b gh-pages
      - run: git pull
      - run: git push --set-upstream origin gh-pages
